[package]
name = "mosaic"
version = "0.1.0"
authors = ["Martin Schenck <martin@ost.com>"]

[dependencies]
web3 = "^0.3.1"
log = "^0.4.3"
simple_logger = "^0.5.0"
[dependencies.clap]
    features = ["yaml"]
